cc_library(
  name = "deathmatch_mode",
  deps = [
  ],
  srcs = ["deathmatch_mode.cc"],
  hdrs = ["deathmatch_mode.h"],
  visibility = [
    "//src:__pkg__"
  ],
)

cc_library(
  name = "league_mode",
  deps = [
  ],
  srcs = ["league_mode.cc"],
  hdrs = ["league_mode.h"],
  visibility = [
    "//src:__pkg__"
  ],
)

cc_library(
  name = "groups_mode",
  deps = [
  ],
  srcs = ["groups_mode.cc"],
  hdrs = ["groups_mode.h"],
  visibility = [
    "//src:__pkg__"
  ],
)