cc_library(
  name = "player",
  deps = [
  ],
  srcs = ["player.cc"],
  hdrs = ["player.h"],
  visibility = [
    "//src:__subpackages__",
  ],
)

cc_library(
  name = "team",
  deps = [
    ":player"
  ],
  srcs = ["team.cc"],
  hdrs = ["team.h"],
  visibility = [
    "//src:__subpackages__",
  ],
)