cc_library(
  name = "contestant_factory",
  deps = [
    "//src/entities:contestant",
    "//src/entities/creators:contestant_creator",
  ]
  srcs = ["contestant_factory.cc"],
  hdrs = ["contestant_factory.h"],
)